package com.dividedby0.victorymod;

import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.suggestion.SuggestionsBuilder;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.commands.SharedSuggestionProvider;
import net.minecraft.core.BlockPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.nbt.NbtIo;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate;
import net.minecraftforge.event.RegisterCommandsEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.fml.loading.FMLPaths;

public class DebugCommands {

    public static void init() {
        MinecraftForge.EVENT_BUS.register(DebugCommands.class);
    }

    @SubscribeEvent
    public static void onRegisterCommands(RegisterCommandsEvent event) {
        event.getDispatcher().register(
            Commands.literal("victorymod")
                .requires(source -> source.hasPermission(2))
                .then(Commands.literal("place")
                    .then(Commands.argument("structure", StringArgumentType.word())
                        .suggests((context, builder) -> suggestStructures(builder))
                        .executes(context -> placeStructure(context.getSource(), StringArgumentType.getString(context, "structure")))))
                .then(Commands.literal("export")
                    .then(Commands.argument("structure", StringArgumentType.word())
                        .suggests((context, builder) -> suggestProceduralStructures(builder))
                        .executes(context -> exportStructure(context.getSource(), StringArgumentType.getString(context, "structure")))))
        );
    }

    private static int placeStructure(CommandSourceStack source, String structureName) {
        ServerLevel level = source.getLevel();
        BlockPos pos = BlockPos.containing(source.getPosition());
        boolean placed = StructureSpawner.placeStructureByName(level, structureName, pos);
        if (placed) {
            source.sendSuccess(() -> Component.literal("Placed " + structureName + " at " + format(pos)), true);
            return 1;
        }

        source.sendFailure(Component.literal("Failed to place " + structureName + " at " + format(pos)));
        return 0;
    }

    private static java.util.concurrent.CompletableFuture<com.mojang.brigadier.suggestion.Suggestions> suggestStructures(
        SuggestionsBuilder builder
    ) {
        return SharedSuggestionProvider.suggest(StructureSpawner.getStructureNames(), builder);
    }

    private static java.util.concurrent.CompletableFuture<com.mojang.brigadier.suggestion.Suggestions> suggestProceduralStructures(
        SuggestionsBuilder builder
    ) {
        return SharedSuggestionProvider.suggest(ProceduralStructures.getProceduralNames(), builder);
    }

    private static int exportStructure(CommandSourceStack source, String structureName) {
        if (!ProceduralStructures.supports(structureName)) {
            source.sendFailure(Component.literal("No autogenerated exporter exists for " + structureName));
            return 0;
        }

        ServerLevel level = source.getLevel();
        BlockPos playerPos = BlockPos.containing(source.getPosition());
        int exportY = Math.min(level.getMaxBuildHeight() - 48, Math.max(level.getMinBuildHeight() + 32, playerPos.getY() + 64));
        BlockPos origin = new BlockPos(playerPos.getX(), exportY, playerPos.getZ());
        ProceduralStructures.Spec spec = ProceduralStructures.getSpec(structureName);

        clearBox(level, spec.paddedStart(origin), spec.paddedEnd(origin));
        ProceduralStructures.place(level, structureName, origin);

        StructureTemplate template = new StructureTemplate();
        template.setAuthor("Codex");
        template.fillFromWorld(level, spec.start(origin), spec.size(), false, Blocks.STRUCTURE_VOID);
        CompoundTag tag = template.save(new CompoundTag());

        try {
            Path projectRoot = FMLPaths.GAMEDIR.get().toAbsolutePath().getParent();
            if (projectRoot == null) {
                source.sendFailure(Component.literal("Could not resolve project root from game directory"));
                return 0;
            }

            Path srcPath = structureOutputPath(projectRoot.resolve("src/main/resources"), structureName);
            Path buildPath = structureOutputPath(projectRoot.resolve("build/resources/main"), structureName);

            Files.createDirectories(srcPath.getParent());
            Files.createDirectories(buildPath.getParent());
            NbtIo.writeCompressed(tag, srcPath.toFile());
            NbtIo.writeCompressed(tag, buildPath.toFile());

            ResourceLocation id = ResourceLocation.fromNamespaceAndPath("victorymod", structureName);
            level.getStructureManager().remove(id);

            clearBox(level, spec.paddedStart(origin), spec.paddedEnd(origin));
            source.sendSuccess(
                () -> Component.literal("Exported " + structureName + " to " + srcPath + " and refreshed build resources"),
                true
            );
            return 1;
        } catch (IOException e) {
            source.sendFailure(Component.literal("Failed to export " + structureName + ": " + e.getMessage()));
            return 0;
        }
    }

    private static Path structureOutputPath(Path root, String structureName) {
        return root.resolve(Path.of("data", "victorymod", "structures", structureName + ".nbt"));
    }

    private static void clearBox(ServerLevel level, BlockPos start, BlockPos end) {
        int minX = Math.min(start.getX(), end.getX());
        int minY = Math.min(start.getY(), end.getY());
        int minZ = Math.min(start.getZ(), end.getZ());
        int maxX = Math.max(start.getX(), end.getX());
        int maxY = Math.max(start.getY(), end.getY());
        int maxZ = Math.max(start.getZ(), end.getZ());

        for (int x = minX; x <= maxX; x++) {
            for (int y = minY; y <= maxY; y++) {
                for (int z = minZ; z <= maxZ; z++) {
                    level.setBlock(new BlockPos(x, y, z), Blocks.AIR.defaultBlockState(), 3);
                }
            }
        }
    }

    private static String format(BlockPos pos) {
        return pos.getX() + ", " + pos.getY() + ", " + pos.getZ();
    }
}
